import React from 'react';
import './App.css';
import _ from 'lodash';
import * as nothing from './nothing.jpeg'

function format(string) {
  string = string.replace(/<unk>/g, _.repeat("█", _.random(3, 6)));
  return string.charAt(0).toUpperCase() + string.slice(1);
}


class Artwork extends React.Component {
  constructor(props) {
    super(props);
    this.state = {disabled: false, images: [], image: {url: nothing, description: "..."} };
    this.onArtUpdate = this.onArtUpdate.bind(this);
  }

  onArtUpdate(e) {
    e.preventDefault();
    const newImage = _.sample(this.state.images);
    this.setState({disabled: true, image: newImage})
  }

  componentWillMount() {
    fetch("https://artwork-doesnt-exists.firebaseio.com/images.json")
    .then(data => data.json())
    .then(state => this.setState({images: state}))
    .then(() => this.setState({image: _.sample(this.state.images)}))
  }

  render() {
    const desc = this.state.disabled ? "..." : format(this.state.image.description);

    return (
    <div className="artwork">
      <img src={this.state.image.url} onLoad={() => this.setState({disabled: false})}
       className="img-fluid mx-auto d-block" alt={this.state.image.description}/>
      <br />
      <blockquote className="blockquote text-center">
        <h1 className="text-center">"{desc}"</h1>
        <button className={"btn btn-link " + (this.state.disabled ? 'disabled' : '')}
         onClick={this.onArtUpdate}>Press me to generate new art!</button>
      </blockquote>
    </div>
    );
  }
}

function App() {
  return (
  <div className="container">
    <Artwork />
    <footer className="navbar sticky-bottom">
      <p className="blockquote text-center text-muted w-100">
      <i>Generated by <a href="http://stylegan.xyz/video">AI</a>, Trained by Human</i>
      </p>
      </footer>
  </div>
  );
}

export default App;
